services:
  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  mongodb_data: