services:
  valkey:
    image: bitnami/valkey:latest
    ports:
      - 16379:6379
    volumes:
      - valkey_data:/bitnami/valkey/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  valkey_data: